Repository Radioaction-Cyber/Age-of-Psydon, pull requests merged in 2025-04, with the labels that each got.

#49 Temporary Removal of Mercenary and Guild Clerk
  code/modules/jobs/job_types/roguetown/mercenaries/guild_clerk.dm
  code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm
Labels: Balance

#50 Keep Over-haul
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#51 Manor's security balance. (Additional changes to the Marshal/councilor's rooms.
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#55 Keep update
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#57 Update Pt2 - Market
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#66 Unironic Bandit Buff (not really)
  code/modules/antagonists/roguetown/villain/bandit.dm
  code/modules/jobs/job_types/roguetown/bandits/bandit.dm
  code/modules/jobs/job_types/roguetown/bandits/types/brigand.dm
  code/modules/jobs/job_types/roguetown/bandits/types/foresworn.dm
  code/modules/jobs/job_types/roguetown/bandits/types/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/bandits/types/knave.dm
  code/modules/jobs/job_types/roguetown/bandits/types/roguemage.dm
  code/modules/jobs/job_types/roguetown/bandits/types/sawbones.dm
  code/modules/roguetown/roguejobs/miner/rogueores.dm
Labels: Balance

#65 Scholar's shop
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#67 Mace Meta Cucked
  code/game/objects/items/rogueweapons/melee/blunt.dm
  code/game/objects/items/rogueweapons/melee/polearms.dm
Labels: Test Merge

#68 Werevolf rebalance
  code/modules/mob/living/carbon/human/species_types/roguetown/other/werewolf.dm
Labels: Test Merge

#72 Lowtown Overhaul - Test 1
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#77 OH FUCK OH SHIT / LAST MINUTE FIXES
  code/modules/jobs/job_types/roguetown/bandits/bandit_vet.dm
  code/modules/jobs/job_types/roguetown/bandits/types/roguemage.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
  code/modules/jobs/job_types/roguetown/towners/types/peasant.dm
  roguetown.dme
Labels: Balance

#81 PLZ MERGE
  code/modules/jobs/job_types/roguetown/bandits/bandit_vet.dm
Labels: Balance

#84 Playtest changes part 1
  code/controllers/subsystem/ticker.dm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/manorguard.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/steward.dm
  code/modules/jobs/job_types/roguetown/peasants/soilson.dm
Labels: Balance

#85 Playtest changes part 2
  code/__DEFINES/roguetown.dm
  code/__DEFINES/traits.dm
  code/datums/gods/patrons/psydon.dm
  code/datums/weather/weather_types/roguetown/rain.dm
  code/modules/jobs/job_types/roguetown/bandits/bandit_vet.dm
  code/modules/jobs/job_types/roguetown/bandits/types/brigand.dm
  code/modules/jobs/job_types/roguetown/bandits/types/foresworn.dm
  code/modules/jobs/job_types/roguetown/bandits/types/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/bandits/types/knave.dm
  code/modules/jobs/job_types/roguetown/bandits/types/roguemage.dm
  code/modules/jobs/job_types/roguetown/bandits/types/sawbones.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Balance

#86 Updates roguetest for new needs
  _maps/map_files/roguetest/roguetest.dmm
  code/modules/clothing/rogueclothes/storage/storage.dm
  code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
Labels: Mapping

#89 HugeUpdate-TEST
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#91 Hand and Consort balance (mostly)
  code/datums/migrants/migrant_waves/heartfelt roles.dm
  code/modules/jobs/job_types/roguetown/nobility/consort.dm
  code/modules/jobs/job_types/roguetown/nobility/hand.dm
  code/modules/jobs/job_types/roguetown/nobility/ruler.dm
Labels: Balance

#93 Guts Servant Subclasses
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
Labels: Balance

#97 Keep-Updates Part 3 (Test)
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#98 BANDIT FIXES 2.0 / BOB CAN'T CODE EDITION
  code/modules/cargo/packsrogue/bandit/consumables.dm
  code/modules/jobs/job_types/roguetown/bandits/bandit.dm
  code/modules/jobs/job_types/roguetown/bandits/bandit_vet.dm
Labels: Balance

#100 MoreKeepEdits- Part 4
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#101 TestEdits- Part5
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#103 Final Touch-up Edits
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#102 TESTMERGE THIS, I'M BAD AT CODING / Servant PQ fix and bandit vet spawn point addition as well as courier
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
Labels: invalid, Balance

#106 Update knight.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
Labels: Balance

#107 Removal of Architect and Artificer
  code/modules/jobs/job_types/roguetown/yeomen/architect.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificier.dm
Labels: Balance

#108 ARMOR AND HOARD FIXES 1
  code/modules/cargo/packsrogue/bandit/brigand.dm
  code/modules/cargo/packsrogue/bandit/foresworn.dm
  code/modules/cargo/packsrogue/bandit/gear.dm
  code/modules/cargo/packsrogue/luxury.dm
  code/modules/clothing/rogueclothes/cloaks/cloaks.dm
  code/modules/clothing/rogueclothes/hats/hats.dm
  code/modules/clothing/rogueclothes/shoes/shoes.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
Labels: Balance

#113 More keep edits
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#114 Revert "Update knight.dm"
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
Labels: Balance

#119 LaunchEdits
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#121 MillEdit
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#123 Quick Changes
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/structures/mineral_doors.dm
  code/modules/clothing/rogueclothes/storage/storage.dm
  code/modules/jobs/job_types/roguetown/towners/types/blacksmith.dm
  code/modules/jobs/job_types/roguetown/towners/types/fisher.dm
  code/modules/jobs/job_types/roguetown/towners/types/peasant.dm
  code/modules/jobs/job_types/roguetown/towners/types/seamster.dm
  code/modules/jobs/job_types/roguetown/towners/types/towndoctor.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
  code/modules/jobs/job_types/roguetown/yeomen/seamster.dm
  code/modules/jobs/job_types/roguetown/youngfolk/smith_apprentice.dm
  code/modules/roguetown/roguejobs/cook/tools/pot.dm
Labels: Balance

#122 Merchant/Village Update
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#124 Starters
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#126 Village Door ID's
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping
