Repository Radioaction-Cyber/Age-of-Psydon, pull requests merged in 2025-03, with the labels that each got.

#4 Map Revert
  _maps/map_files/rockhill/rockhill.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/roguetown/mercenaries/guild_clerk.dm
  code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm
  code/modules/jobs/job_types/roguetown/other/tester.dm
Labels: Balance, Mapping

#6 Courier Guild building, a bit of Demolition on the side
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#7 Rockhill final check over on Hermes cleanup
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#9 Removal of non-functional dungeon entrance
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#12 Trog's "For the love of Dungeons!!"
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping, Test Merge

#10 CHURCH
  code/modules/jobs/job_types/roguetown/church/druid.dm
  code/modules/jobs/job_types/roguetown/church/monk.dm
  code/modules/jobs/job_types/roguetown/church/mortician.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
Labels: Balance, Test Merge

#13 COURTIER
  code/modules/jobs/job_types/roguetown/courtier/councillor.dm
  code/modules/jobs/job_types/roguetown/courtier/jester.dm
  code/modules/jobs/job_types/roguetown/courtier/magician.dm
  code/modules/jobs/job_types/roguetown/courtier/physician.dm
Labels: Balance, Test Merge

#16 INQUIS
  code/modules/jobs/job_types/roguetown/inquisition/confessor.dm
  code/modules/jobs/job_types/roguetown/inquisition/puritan.dm
Labels: Balance, Test Merge

#18 PEASANTS
  code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
  code/modules/jobs/job_types/roguetown/peasants/beggar.dm
  code/modules/jobs/job_types/roguetown/peasants/bogprisoner.dm
  code/modules/jobs/job_types/roguetown/peasants/butcher.dm
  code/modules/jobs/job_types/roguetown/peasants/cook.dm
  code/modules/jobs/job_types/roguetown/peasants/hostage.dm
  code/modules/jobs/job_types/roguetown/peasants/nightman.dm
  code/modules/jobs/job_types/roguetown/peasants/prisoner.dm
  code/modules/jobs/job_types/roguetown/peasants/soilson.dm
Labels: Balance, Test Merge

#21 YEOMEN
  code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
  code/modules/jobs/job_types/roguetown/yeomen/artificier.dm
  code/modules/jobs/job_types/roguetown/yeomen/barkeep.dm
  code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
Labels: Balance, Test Merge

#22 YOUNGFOLK / WHAT YOU LEAVE FOR YOUR SONS
  code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
  code/modules/jobs/job_types/roguetown/youngfolk/clerk.dm
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
Labels: Balance

#15 TOWNWATCH
  code/modules/clothing/rogueclothes/hats/hats.dm
  code/modules/jobs/job_types/roguetown/garrison/townwatch/citywatch.dm
  code/modules/jobs/job_types/roguetown/garrison/townwatch/types/watcharcher.dm
  code/modules/jobs/job_types/roguetown/garrison/townwatch/types/watchfootman.dm
  code/modules/jobs/job_types/roguetown/garrison/townwatch/types/watchhalberdier.dm
Labels: Balance, Test Merge

#23 1
  code/modules/jobs/job_types/roguetown/bandits/types/brigand.dm
  code/modules/jobs/job_types/roguetown/bandits/types/foresworn.dm
  code/modules/jobs/job_types/roguetown/bandits/types/knave.dm
  code/modules/jobs/job_types/roguetown/bandits/types/roguemage.dm
  code/modules/jobs/job_types/roguetown/bandits/types/sawbones.dm
Labels: Balance

#26 Troglodite overall (marketplace, and stalls for all)
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping, Test Merge

#27 Update rockhill.dmm
  _maps/map_files/rockhill/rockhill.dmm
Labels: invalid, Mapping

#33 Marketplace Fixes
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#34 Bandit QoL and Hood Revert
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/jobs.dm
  code/modules/clothing/rogueclothes/hats/hats.dm
  code/modules/jobs/job_types/roguetown/bandits/bandit_vet.dm
Labels: Balance, Mapping

#37 Return of the Boggard (and Manor Guard)
  code/game/gamemodes/roguetown/roguetown.dm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/rogueclothes/cloaks/cloaks.dm
  code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
  code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/manorguard.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/types/archer.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/types/footman.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/types/halberdier.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/types/veteran.dm
  code/modules/roguetown/roguecrafting/sewing.dm
  code/rt.dm
Labels: Balance

#38 The King Returns (and Queen)
  _maps/map_files/rockhill/rockhill.dmm
  code/game/objects/effects/landmarks.dm
  code/modules/clothing/rogueclothes/armor/armor.dm
  code/modules/jobs/job_types/roguetown/nobility/consort.dm
  code/modules/jobs/job_types/roguetown/nobility/ruler.dm
Labels: Balance, Mapping

#39 Merchant Vault and Keep Vault revamp
  _maps/map_files/rockhill/rockhill.dmm
  code/game/objects/items/rogueitems/coins.dm
Labels: Mapping

#40 WHEN
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/roguetown/bandits/bandit.dm
  code/modules/jobs/job_types/roguetown/bandits/bandit_vet.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/manorguard.dm
Labels: Balance

#43 No Dig Zones
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping

#42 CAN'T
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/manorguard.dm
  code/modules/jobs/job_types/roguetown/garrison/manatarms/types/footman.dm
  code/modules/jobs/job_types/roguetown/garrison/sheriff.dm
  code/modules/jobs/job_types/roguetown/garrison/townwatch/citywatch.dm
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
  code/modules/jobs/job_types/roguetown/inquisition/puritan.dm
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/jobs/job_types/roguetown/nobility/knight.dm
Labels: Balance

#44 Marketplace Rework
  _maps/map_files/rockhill/rockhill.dmm
Labels: Mapping, Test Merge
